apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: eu-north-1

managednodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
